### ISSUE TITLE
Navstack crashes when resetting and starting lifecycle nodes

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#1121]
In #1108, the buttons expose the ability to `reset` and `startup` the stack, however, the navstack will crash when attempting to startup after the lifecycle nodes have been reset (`on_cleanup`). Below is a tracking list of bugs that I have seen when attempting to transition back to the active state:

- [X] Declaring already declared parameters (#1099, #1137)
- [X] ClassLoader bug (fixed with https://github.com/ros/class_loader/pull/127)
- [X] NavfnPlanner costmap is reset (fixed with #1123)
- [X] BtNavigator action server error (#1139)
- [X] Amcl map is null (#1141)

**Comment by bpwilcox** [comment]
Highlighted bugs have been fixed with merged PRs. Closing
