### ISSUE TITLE
What changes should go into the 0.2.5 release? (End of Sept release)

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1187]
This is the set of commits that have gone into master since the 0.2.4 release. What commits should go into 0.2.5?

- [ ] a05c9440 2019-10-01 'Carl Delsey' Sphinx Docs - Template Only (#1138)
- [ ] a0a9eb23 2019-10-01 'Steven Macenski' Merge pull request #1176 from SteveMacenski/wait_Recovery
- [ ] 691abe36 2019-10-01 'stevemacenski' using builtin msgs duration
- [ ] ec834a5d 2019-10-01 'Carlos A. Orduno' [multirobot - Part4] Multiple robot control via RVIZ (#1178)
- [ ] 21a3b113 2019-10-01 'stevemacenski' check for negative or zero values in duration
- [ ] e9e96a39 2019-10-01 'stevemacenski' remove unnecessary indentations
- [ ] 2c84c534 2019-09-30 'stevemacenski' adding wait recovery into recovery behavior tree
- [ ] 0d21ddd4 2019-09-30 'stevemacenski' removing extraneous copy of extra bt
- [ ] e17b29ef 2019-09-30 'stevemacenski' wait recovery behavior
- [ ] 4d80d5d3 2019-09-30 'stevemacenski' nav2 recovery interface for bt navigator wait
- [x] 8e886867 2019-09-30 'Ruffin' Merge pull request #1142 from ros-planning/update_dockerfile
- [x] 818ae9d8 2019-09-19 'ruffsl' Use ament index to resolve rosdep install
- [x] 0df1713b 2019-09-30 'Ruffin' Merge pull request #1158 from ros-planning/ruffsl-patch-1
- [ ] ba9cba71 2019-09-30 'bpwilcox' add sleep before checking for collision, remove nav2_dynamic_params from test suite
- [ ] 46b32957 2019-09-30 'Steven Macenski' Merge pull request #1131 from SteveMacenski/nav2_recovery_server
- [ ] 0fa1a95e 2019-09-30 'Carlos A. Orduno' [multirobot - Part3] Add multi-robot launching (#1148)
- [x] e96d1851 2019-09-30 'ruffsl' Always build underlay as release
- [ ] 180814ba 2019-09-30 'stevemacenski' Merge branch 'master' of github.com:ros-planning/navigation2 into nav2_recovery_server
- [ ] 7063776a 2019-09-17 'Matthew Hansen' Update behavior tree with local and global recoveries
- [ ] fa82367b 2019-09-30 'stevemacenski' fixing backup recovery crash from null node ptr
- [ ] 9517be78 2019-09-27 'Carlos A. Orduno' Fix linter errors (#1174)
- [ ] 50c3157b 2019-09-27 'stevemacenski' adding onCleanup and declaring params in constructor
- [ ] c9d4241a 2019-09-27 'Steven Macenski' Merge pull request #1169 from Jconn/issues/1160_listen_to_goal_changes
- [ ] 90e7a990 2019-09-26 'Steven Macenski' Merge pull request #1171 from shivaang12/doc-recovery-typo
- [ ] d22b681e 2019-09-26 'Shivang Patel' Fixed documentation typo.
- [ ] bcc9fd0d 2019-09-25 'johnconn' prevent dwb controller from missing changes to the global path (#1160)
- [ ] 226f06ce 2019-09-25 'Carlos A. Orduno' [multirobot] Add namespacing to nav stack. (#1147)
- [ ] a0ee02ea 2019-09-25 'Carlos A. Orduno' [multirobot] Spawn multiple robots into Gazebo (#1146)
- [ ] 9c061867 2019-09-25 'Carlos A. Orduno' Fix planner server time bug (#1165)
- [x] 0bf7f9ce 2019-09-25 'Carlos A. Orduno' Enable deprecated warnings (#1167)
- [ ] c0777fb9 2019-09-25 'bpwilcox' check for always_reset_initial_pose flag in configure step
- [ ] 0828c894 2019-09-23 'bpwilcox' reset initial pose with last known pose covariances
- [x] 2d368caf 2019-09-25 'Carlos Orduno' Fix typo
- [ ] e40ffaf5 2019-09-25 'stevemacenski' unique ptrs from shared ptrs
- [ ] 78a0272c 2019-09-24 'Melih Erdogan' Navigation 2 with SLAM Documentation (#1143)
- [x] 1193dbc9 2019-09-24 'Carlos A. Orduno' Update design for providing transform to bt nodes (#1157)
- [ ] 700f3655 2019-09-24 'stevemacenski' shared recovery ptrs to unique
- [x] e9734e00 2019-09-24 'Ruffin' Add test for rmw_cyclonedds_cpp to nightly job
- [ ] 206105cf 2019-09-24 'stevemacenski' update recoveies_server_node -> recoveries_server & other feedback
- [x] da9cec63 2019-09-23 'Ruffin' Simplify checksum commands for consistency
- [x] f4e70486 2019-09-23 'Ruffin' Include complete path of checksum.txt in checksum
- [x] 555bd7fb 2019-09-23 'Ruffin' Fix underlay parameter for install_overlay_dependencies
- [ ] 8b8985ec 2019-09-23 'Steven Macenski' Update test_system_launch.py
- [ ] 704dbaf3 2019-09-23 'stevemacenski' add memory header to recovery.hpp
- [ ] b7c6761a 2019-09-22 'bpwilcox' fix rebase issues / modify for autostart fix
- [ ] 5f37f6e8 2019-09-10 'bpwilcox' add pause, resume, and repeat button transitions
- [ ] 544e06f3 2019-09-10 'bpwilcox' add pausing/resuming states and slots
- [ ] 5da8e211 2019-09-17 'bpwilcox' fix rebase issue
- [ ] e6092fa6 2019-09-17 'bpwilcox' return system status with timeout
- [ ] 535aba09 2019-09-05 'bpwilcox' lint and uncrustify cleanup
- [ ] 1f28d27a 2019-09-04 'bpwilcox' add service/client for active system and call in Qthread
- [ ] d8ab5d2a 2019-09-20 'stevemacenski' fix merge conflict
- [ ] 0c611bac 2019-09-20 'stevemacenski' merge commit
- [ ] decb36fc 2019-09-20 'Dan Rose' Change "the system" to "managed nodes"
- [ ] 5f96f5b3 2019-09-18 'bpwilcox' create action server on BtNavigator node
- [ ] cc50e2e6 2019-09-19 'bpwilcox' set first_map_received to false when cleaning up
- [ ] 030a0e1d 2019-09-18 'bpwilcox' declare_parameter_if_not_declared in navfnplanner
- [ ] ea0524fb 2019-09-19 'Yathartha Tuladhar' dwb_core.xml
- [ ] 550e1d85 2019-09-17 'Yathartha Tuladhar' Plugin naming cleanup
- [ ] ddb24c55 2019-09-16 'Yathartha Tuladhar' Addressing GCC diagnostic push, pop suggestion
- [ ] c0bc5314 2019-09-14 'Yathartha Tuladhar' 
- [ ] b900d0c4 2019-09-13 'Yathartha Tuladhar' Cleanups and renames
- [ ] 65eb602e 2019-09-13 'Yathartha Tuladhar' Renaming, cleanup, and reintroduced TF buffer
- [ ] 176dc7db 2019-09-12 'Yathartha Tuladhar' Fix linters and delete unused files
- [ ] f5109950 2019-09-12 'Yathartha Tuladhar' Enabling 3D messages for the planner interface
- [ ] 243a8c78 2019-09-12 'Yathartha Tuladhar' Using dwb as plugin
- [ ] 387d0320 2019-09-12 'Yathartha Tuladhar' Creating nav2_controller, and deleting dwb_controller
- [ ] 597c9186 2019-09-12 'Yathartha Tuladhar' nav2_core interface, with lifecycle changes and cleanup
- [x] f2a9fb7a 2019-09-19 'Ruffin' Merge pull request #1127 from ros-planning/update_dockerfile
- [ ] 77f3a618 2019-09-19 'Yathartha Tuladhar' Merge pull request #1140 from yathartha3/params_file
- [x] c9b497bc 2019-09-17 'ruffsl' Colcon mixin now installed from base image
- [x] 919aa32c 2019-09-19 'Ruffin' Merge pull request #1122 from ruffsl/multistage_cache
- [x] 35e80f41 2019-09-19 'ruffsl' Cache both underlay and overlay layers
- [ ] e486ae25 2019-09-19 'Yathartha Tuladhar' Fix params file path
- [x] b49a4699 2019-09-17 'Ruffin' Update labels
- [x] a1097607 2019-09-17 'Ruffin' Comment new directives
- [x] 6de6f2d2 2019-09-17 'Ruffin' Revert FROM tag change
- [x] ce1724d1 2019-09-16 'ruffsl' Include COLCON_IGNORE in cache
- [x] dce46bf0 2019-09-16 'ruffsl' Cache per packge.xml via multistage
- [ ] 0bfa19c9 2019-09-18 'bpwilcox' fix deprecated publisher api issues (#1133)
- [ ] 44dcd605 2019-09-17 'Carlos A. Orduno' Refactored launch files (#1118)
- [ ] 2f6bb041 2019-09-17 'stevemacenski' Merge branch 'master' of github.com:ros-planning/navigation2 into nav2_recovery_server
- [ ] bab0e81d 2019-09-17 'stevemacenski' setting up on each fixture
- [ ] 89da35da 2019-09-17 'stevemacenski' add more useful logging to test
- [ ] de0aba5e 2019-09-17 'stevemacenski' recoveries server bringup with lifecycle
- [ ] 5ef79f72 2019-09-17 'Steven Macenski' Merge pull request #1132 from rotu/patch-2
- [ ] 03775f6c 2019-09-17 'Dan Rose' Update lifecycle_manager_client.cpp
- [ ] ccefa77f 2019-09-17 'stevemacenski' setting global transform listener and buffer
- [ ] a133dfdc 2019-09-17 'stevemacenski' linting nav2_recoveries
- [ ] 16fda6af 2019-09-17 'Steven Macenski' Merge pull request #1128 from SteveMacenski/nukes
- [ ] 9142f21f 2019-09-17 'stevemacenski' remove nav2_dynamic_parameters
- [ ] 448ee32a 2019-09-16 'bpwilcox' remove reset of costmap_ros shared ptr
- [ ] 8ee2726e 2019-09-16 'stevemacenski' adding plugins
- [ ] 68ba0831 2019-09-16 'stevemacenski' templating node type for action server
- [ ] cd22a7b6 2019-09-16 'stevemacenski' properly registering plugins
- [ ] 7c3dca23 2019-09-16 'stevemacenski' spin should also work in other direction for singularity
- [ ] 99f05189 2019-09-16 'stevemacenski' temporarily removing executeRecovery method for further discussion
- [ ] 1ff6bb76 2019-09-16 'stevemacenski' adding first prototypes of spin/backup recoveries
- [ ] 4c3e7881 2019-09-16 'stevemacenski' adding pluginlib dependencies
- [ ] 61eb3829 2019-09-16 'stevemacenski' update recovery and global planner to use shared_ptr tf buffers
- [ ] 11b73c35 2019-09-16 'stevemacenski' changing bringup for new recoveries servern ode
- [ ] 2b9f87e9 2019-09-16 'stevemacenski' nav2 recovery server loading via pluginlib
- [ ] 44a0a6f7 2019-09-16 'stevemacenski' build with recovery server
- [ ] ff9352eb 2019-09-16 'stevemacenski' update nav2_recoveries to consume nav2_core
- [ ] 4973026a 2019-09-16 'Yathartha Tuladhar' updated setting of ros-args (#1120)
- [ ] 1781a5b9 2019-09-13 'Steven Macenski' Merge pull request #1117 from SteveMacenski/planner_pkg2
- [ ] 6753cd6d 2019-09-13 'stevemacenski' move costmap in nav2_planner to shared_ptr and node to rclcpp lifecycle
- [ ] a2b8ed99 2019-09-13 'Steven Macenski' Merge pull request #1107 from SteveMacenski/planner_pkg
- [x] 32d36f80 2019-09-13 'Ruffin' Merge pull request #1115 from crdelsey/circleci-rosdep
- [ ] 3e05f5de 2019-09-13 'Carl Delsey' Add current workspace to the rosdep install command
- [ ] 3112a3d1 2019-09-13 'stevemacenski' review comment update for nav2_planner
- [ ] fa92240d 2019-09-13 'Carl Delsey' Fix execute process calls to use new parameter format. (#1113)
- [ ] 7a8ab473 2019-09-05 'bpwilcox' remove extra Qstates and rename idle state
- [ ] e60db7c6 2019-09-05 'Melih Erdogan' removed the apt-get install dependency list
- [ ] e72a5237 2019-08-30 'Melih Erdogan' added a new dependency to the list and updated ROS 2 dependencies the link
- [ ] ee184fc4 2019-09-12 'Matt Hansen' Delete .gitignore
- [ ] 173206ce 2019-09-05 'Carl Delsey' Fixing missing boost dependency
- [ ] 19e30bdd 2019-09-05 'Carl Delsey' Fix dependency exports
- [ ] 816db291 2019-09-11 'Dan Rose' Remove backticks
- [ ] a8ffd734 2019-09-09 'Dan Rose' Adjust issue template
- [ ] 577fb6cd 2019-09-11 'stevemacenski' nav2_utils->nav2_util
- [ ] 0d863052 2019-09-11 'bpwilcox' fix uncrustify
- [ ] f6379818 2019-09-11 'bpwilcox' add ros args flag to costmap
- [ ] 19dd3302 2019-09-10 'Matthew Hansen' ucrustify static layer
- [ ] cc5b9bbf 2019-09-10 'Matthew Hansen' Fix typo -initialized-
- [ ] 884483fa 2019-09-10 'Matthew Hansen' Throw runtime_error instead of string
- [ ] 446ae7f3 2019-09-10 'Matthew Hansen' Remove try/catch for updateMap()
- [ ] f4e7b485 2019-09-10 'Matthew Hansen' Change ERROR to throttled WARN
- [ ] 7a4d5988 2019-08-30 'Melih Erdogan' in static layer set a flag to check if map is received
- [ ] 02161501 2019-08-30 'Melih Erdogan' throw exception when costmap is not initialized
- [ ] 445fe6f4 2019-08-22 'Matthew Hansen' Add support for running nav2 with cartographer
- [ ] 82851632 2019-09-11 'stevemacenski' readding intel copyright headers
- [ ] 9c4367d6 2019-09-11 'Steven Macenski' Update nav2_planner/src/planner_server.cpp
- [ ] 8e6b959a 2019-09-11 'Steven Macenski' Update nav2_navfn_planner/src/navfn_planner.cpp
- [ ] b0eda858 2019-09-11 'Steven Macenski' Update nav2_navfn_planner/src/navfn_planner.cpp
- [ ] 82f56f78 2019-09-11 'Steven Macenski' Update nav2_navfn_planner/README.md
- [ ] c6ec5647 2019-09-11 'stevemacenski' replace navfn_planner lifecycle bringup with nav2_planner
- [x] ec34755f 2019-09-10 'Ruffin' Merge pull request #1106 from ruffsl/rm_colcon_ignore
- [ ] 446925e9 2019-09-10 'stevemacenski' refining nav planner plugin for use in the nav2_planner
- [ ] 85f32dc2 2019-09-10 'stevemacenski' updating shared ptr for use in the global planner plugin
- [x] 51e8663e 2019-09-10 'Ruffin' Revert branch typo
- [ ] af402c53 2019-09-10 'stevemacenski' registering pluginlib global planner plugin
- [ ] ccc36177 2019-09-10 'Matthew Hansen' Add arguments for joint state remapping
- [ ] 45652529 2019-09-09 'Carl Delsey' Adding -r and --ros-args where needed.
- [ ] cf530044 2019-09-09 'Matthew Hansen' Add QOS policies to system test
- [ ] c79b4328 2019-09-09 'Matthew Hansen' Change test world to use new arguments flags
- [x] eec7127d 2019-09-10 'ruffsl' Remove COLCON_IGNORE
- [ ] e342010b 2019-08-30 'bpwilcox' integrate declare if not declared parameters through dwb
- [ ] 0e1e7653 2019-08-30 'bpwilcox' declare if not declared parameters for costmap plugins
- [ ] 867b03b3 2019-09-10 'stevemacenski' update documents for nav2_planner with navfn plugin
- [ ] 7dee2eaf 2019-09-10 'stevemacenski' adding nav2_planner to bringup
- [ ] b1b33bf1 2019-09-10 'stevemacenski' base nav2 planning server
- [ ] a473526f 2019-09-10 'stevemacenski' navfn package to plugin
- [ ] 92a50aa6 2019-09-10 'stevemacenski' updating dwb for removal of nav2_msgs
- [ ] fc9ab5d2 2019-09-10 'stevemacenski' updating global and recovery base type headers
- [ ] 465e4e1d 2019-09-10 'stevemacenski' removing nav2_msgs/path in favor of nav_msgs/Path which inherently contains more information
- [ ] 41da7b80 2019-09-10 'Steven Macenski' Merge pull request #1089 from SteveMacenski/model_navfn
- [ ] 0c5641ff 2019-09-10 'Steven Macenski' Merge pull request #1101 from lopsided98/map-loader-sdl-include
- [ ] 71d5d715 2019-09-10 'stevemacenski' change default state in case of first hit TF failure & hundred test 3 times for similar
- [ ] 4efa7357 2019-09-10 'stevemacenski' removing overloaded collision/tolerance methods
- [ ] 675717da 2019-09-10 'stevemacenski' add activation in node tests
- [ ] 50bb9131 2019-09-10 'stevemacenski' merge conflict resolution from global planner test updates
- [ ] 6993fcd9 2019-09-09 'Carlos A. Orduno' Improvements to global planner tests (#1083)
- [ ] 41eeab2d 2019-09-09 'stevemacenski' updating versions to current 0.2.4
- [ ] 183d6ece 2019-09-09 'stevemacenski' moving cost_value header from navfn_planner.hpp to .cpp
- [ ] b87942a3 2019-09-06 'Ben Wolsieffer' map_loader: add SDL include directories
- [ ] 0514c9aa 2019-09-06 'stevemacenski' removing debug artifacts
- [ ] cba1e8cf 2019-09-05 'bpwilcox' change srv name, remove msg
- [ ] d5f1dcc3 2019-08-29 'bpwilcox' fix lint and uncrustify issues
- [ ] 0363a174 2019-08-29 'bpwilcox' remove reason srv string
- [ ] 5aa6b51b 2019-08-29 'bpwilcox' add pause, resume, reset to manager client
- [ ] f5ef0d06 2019-08-28 'bpwilcox' create custom lifecycle manager srv
- [ ] 94f06fb9 2019-08-28 'bpwilcox' configure and activate all nodes separately
- [ ] 240bcef7 2019-09-05 'Steven Macenski' Merge pull request #1087 from SteveMacenski/nav2_core
- [ ] e18090ba 2019-09-05 'stevemacenski' update licenses in nav2_core to be Apache
- [ ] 41a48739 2019-09-04 'stevemacenski' updating nav_core2 license to apache
- [ ] 78854bdb 2019-09-04 'stevemacenski' plugins receive lifecycle node pointers
- [ ] fb25e8fd 2019-09-04 'stevemacenski' fixed CI issues from incorrect static map state and others

**Comment by orduno** [comment]
(I'll be updating this comment as check more items from the list)

Checked items:
- Checking https://github.com/ros-planning/navigation2/commit/1193dbc90690944dd01ccc85736cf3ff021f0f1e as there's an issue reported the bug on Dashing.
- https://github.com/ros-planning/navigation2/commit/0bf7f9ce3eb1862271ccb329d515df653a24f32b is kind of minor, doesn't hut getting in.

Questions:
- We got a long list :fearful:. Can we discuss in general what features we want in? We have:
  - Multi-robot
  - Global planner refactors
  - Local planner refactors
  - Recoveries refactors
  - etc...

**Comment by crdelsey** [comment]
> We got a long list. 

Yeah. Tell me about it. I kind of gave up last month on being surgical and just merged everything. That lead to merging something that shouldn't have been merged. I would not have known it wasn't supposed to be merged, though. I think we need the authors, or at least someone familiar with the change to make the call on whether it should be backported. It would be nice if we added a flag to PRs to say whether we want to backport or not, but right now, there's no way to enforce that.

> Can we discuss in general what features we want in?

After discussing a bit yesterday, I'm of the opinion we just want to back port bug fixes to dashing at this point. Eloquent is not that far away, and Dashing is usable, so we don't need to back port features

**Comment by SteveMacenski** [comment]
> After discussing a bit yesterday, I'm of the opinion we just want to back port bug fixes to dashing at this point. Eloquent is not that far away, and Dashing is usable, so we don't need to back port features

I think that's typically what OSRF recommends anyhow. I don't necessarily subscribe to that mentality, but there's too much entropy in this project and its not a good use of your time to try to knit-pick features as you've mentioned. :+1: for back porting genuine bugs only

**Comment by mkhansen-intel** [comment]
> After discussing a bit yesterday, I'm of the opinion we just want to back port bug fixes to dashing at this point. Eloquent is not that far away, and Dashing is usable, so we don't need to back port features

Seeing this list I agree.

**Comment by mkhansen-intel** [comment]
I submitted a PR #1193 directly to the dashing devel branch as a bug fix that needs to be merged before 0.2.5

**Comment by ruffsl** [comment]
Any of my commits for patching the CI should be fine, given they don't intersect with the nav2 code. It could help keep the CI consistent when testing PRs for backporting to dashing. Though, I may need to tweek the docker hooks on the dashing branch to switch the executor image from ros2 nightly to dashing.

**Comment by mkhansen-intel** [comment]
@ruffsl - can you check the boxes above for the commits you want backported?

> Though, I may need to tweek the docker hooks on the dashing branch to switch the executor image from ros2 nightly to dashing.

It would be great if you could fix the CI on the dashing branch! :+1:

**Comment by crdelsey** [comment]
@orduno I'm not going to bring in 0bf7f9c, or else I'd also need to bring in the changes that replace the deprecated functions. I don't think we really need that in the dashing release.

**Comment by SteveMacenski** [comment]
@crdelsey #1198 was merged, should I do a release?

**Comment by SteveMacenski** [comment]
closing and doing release
