### ISSUE TITLE
Foxy Release Feature List

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1229]
This is a list of high-level features being considered for the ROS 2 F release.:

- [x] Reduce the number of outstanding issues
- [ ] Support for navigating multi-story buildings #1226
- [x] Behavior tree plugin support #958
- [x] Improve documentation #1228
- [ ] Add support for map zones #404, #401
- [ ] Traffic lanes and routes #1263
- [x] Docking support #1225
- [x] Voxel layer support #955
- [x] Support multiple sensor inputs #1227
- [x] Support for changing maps #239
- [x] Waypoint follower demo #803
- [ ] Improve user experience (TBD)
- [x] Ensure a stable, functional SLAM implementation is available for ROS 2 (outside the nav stack)
- [x] Ensure a stable, functional IMU/Odom fusing solution (eg [Robot Localization] (https://github.com/cra-ros-pkg/robot_localization)) is availble for ROS2. (outside the nav stack) #40 
- [ ] Provide an option/example for launching nav2 using composed nodes #1244
- [x] Add Auto-localization Action server #1254 

Please submit an issue if there is another important feature you'd like to see.

**Please give a  :+1: on any issues that you feel are most important. We will try to prioritize issues that have a lot of community interest.**

**Comment by SteveMacenski** [comment]
I'd add to the list it is my intention within the next 2 releases to replace navfn entirely for a hybrid approach taking into account robot kinematics and footprint. A special case of that would be a circular holonomic robot which would essentially act as navfn.

**Comment by orduno** [comment]
> I'd add to the list it is my intention within the next 2 releases to replace navfn entirely for a hybrid approach taking into account robot kinematics and footprint. A special case of that would be a circular holonomic robot which would essentially act as navfn. This is key for ackermann or non-circular robots

Cool! Let's chat about this, I'm also interested in doing some work on this area.

**Comment by shivaang12** [comment]
> I'd add to the list it is my intention within the next 2 releases to replace navfn entirely for a hybrid approach taking into account robot kinematics and footprint. A special case of that would be a circular holonomic robot which would essentially act as navfn. This is key for ackermann or non-circular robots

Do you mean you want to consider non-holonomic constrains?

**Comment by SteveMacenski** [comment]
Moving tickets into the Foxy milestone, so we don't have redundant lists.

See list here: https://github.com/ros-planning/navigation2/milestone/15
