### ISSUE TITLE
Additional Tests in Stack Metaticket

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1379]
We have a number of tickets scattered describing tests needed, I'd rather have one-stop-shop for all those and close those tickets so that when someone gets an inkling to write some tests, its all in one place. It also cleans up the tickets and groups related work. Since these are more "requests" than bugs or immediate requirements, I suspect these might hang around for awhile.

- [ ] Add lifecycle management system test #1320 
- [ ] BT Navigator system tests #1302 
- [ ] Pluginlib plugin tests #1218 
- [ ] Stack system tests overhaul #1205 
- [ ] Adding additional system test cases #539 
- [ ] Global planner server tests #443 
- [ ] In that same vein controller server tests [no prior ticket]

**Comment by SteveMacenski** [comment]
After changing the coverage metrics, many of these are less important now. If you look at the coverage statistics, many of these are in a pretty good place, though there are certainly places to add more coverage to (we're at 66%, ~80% would be a good steady state point). 

New ticket to be opened about general test updates
