### ISSUE TITLE
Map server design for multi-layer maps, multiple map sources, etc.

### ISSUE THREAD

**Issue by gbiggs** [ros-planning/navigation2#392]
After Crystal is out, there are a number of potential improvements to the functionality of the map server that we can make. Some random ideas of things that could be useful are:

* Allowing a single map server to provide multi-layered maps, with the maps overlaying each other in space and providing different information (one example given is traffic flows to allow robots to avoid crowded areas).
* Allow a map server to load a map from multiple sources. For example, several bitmap files for an occupancy grid map that are then arranged to provide a single map. This allows maps to be managed and maintained in a more granular fashion, especially for larger spaces.
* Merging multiple different map data sources into a single map (single layer) based on processing the data when it is loaded and combining the results in some way.

The purpose of this issue is to get discussion going and identify concrete use cases so that these sorts of features can be implemented in the D Turtle development cycle.

- [ ] #547 Multi-layer maps
- [ ] #548 Maps from sub-map sources
- [ ] #549 Map server providing dynamically-generated maps

**Comment by SteveMacenski** [comment]
The other tickets mentioned above reference the specific action items to implement for map server improvements. 

As this is a metaticket that hasn't been scheduled for working after more than a year, I'm inclined to close it. The actual action items are totally valid and will remain open, but I think a centralized design effort is unlikely to happen at any time in the foreseeable future without a champion.
