### ISSUE TITLE
Enable Motion Primitives for life-cycle design

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#700]
As part of the strategy for #554.

- [x] Change robot class to use node interfaces so it can be used by both lifecycle and regular nodes. #711
- [x] Switch to ROS2 actions within nav2_motion_primitives. #718 
- [x] Update bt nodes related to primitives to use ROS2 actions. #725
