### ISSUE TITLE
Behavior Tree roadmap - meta issue

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#958]
- [x] Port to the 3.0 version of the BT library @crdelsey 
- [ ] Move the Navigation-related BT nodes to a plug-in (supported in the 3.0 library)
- [ ] Move any localization-related nodes (may be required for auto localization) to a separate plug-in
- [ ] Use the XML include capability of the 3.0 library 
- [ ] Split out the generic part of the BT code into a separate repo that can be used by multiple projects
- [ ] generalize a Node API for recoveries to minimize largely redundant action definitions and _node.hpp files @SteveMacenski 
- [x] clear costmap recovery @SteveMacenski

**Comment by SteveMacenski** [comment]
With the plugins I think this is done now.

Still some that can be done to reduce the redundancy in some respects but its not enough to keep a ticket open for
