### ISSUE TITLE
Support multiple robots navigating simultaneously

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#971]
#### Feature description

We'd like to be able to support multiple robots navigating simultaneously on the same system in simulation -- no coordination at this moment, more on that coming soon 😃 

For this we need to:
- [x] If simulation, have Gazebo launch multiple robots (on a single instance) and facilitate launching multiple nav stacks for different robots. #1146, #1148
- [x] Logical partitioning using namespaces for partitioning (grouping services, actions, etc. from a single robot) as a first approach. #1147
- [x] Visualize robots in RVIZ and use plugins to provide initial and goal poses to each robot. #1149

#### Implementation considerations

For partitioning, we have a few options:
- Logical
  - Namespaces
  - DDS Keyed Data (not exposed by ROS2)
  - DDS Domain and Participants (not sure if exposed by ROS2)
- Physical

Most users in ROS1 used separate namespaces for different robots (together with a multi-master pkg). We can replicate that as a starting point, however, there are several reasons we might want an alternative approach, i.e. DDS discovery, Robot encapsulation, etc.

**Comment by SteveMacenski** [comment]
I’m curious why this is given high priority? Running multiple navstacks on multiple robots as is is simple- its mostly a simulation need. Is there someone trying to do this right now we’re blocking?

**Comment by crdelsey** [comment]
We have some bugs relating to being able to partition robots into separate namespaces #746.

We'd also like to be able to run multiple robots in gazebo to get better test coverage. We'd get to run the stack more per test run and also the other robots can act as dynamic obstacles to each other.

**Comment by SteveMacenski** [comment]
Ok, that makes sense, but that also seems like a deterministic nightmare to maintain, but it's good capability to have though in in the N+1 timeframe.

**Comment by orduno** [comment]
Tasks completed so closing the ticket.
